spring:
  application:
    name: shortJ
  datasource:
    url: jdbc:h2:mem:h2db
    username: ${H2_USER}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8081

short-url:
  allowed-chars: ${ALLOWED_CHARS:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}
  key-length: ${SHORT_URL_LENGTH:6}
  std-expiration-minutes: ${STD_EXPIRATION_MINUTES:60}
  hash-salt-secret: ${HASH_SALT_SECRET:my-secret-salt-for-development}

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html